### ISSUE TITLE
Disable Sunday & Monday 

### ISSUE THREAD

**Issue by amyling** [relu/contact-form-7-datepicker#150]
Hello,

I'm running the latest version of WP 4.5.

I'm having issues trying to disable Sunday and Monday. I've googled and used all the code that I could find that worked for other people. 

I tried putting it in the "Additional Settings" tab or in my common.js file but to no avail.

Please help!
Amy

**Comment by hansmosl** [comment]
Hello amyling.

To pick the days of the week you want to show in Jquery UI you can use the **beforeShowDay**.

An live example of that is here in fiddle: http://jsfiddle.net/machadoug/X325G/

Adapting the solution above to your need  (block sundays and mondays) you can simple call all the days. Below the days 0 and 1 (sunday and monday) are ignored.

<script>
jQuery("#RemoveSundaysAndMondays").datepicker({
  beforeShowDay: function(date){ return [date.getDay() == 2 || date.getDay() == 3 || date.getDay() == 4 || date.getDay() == 5 || date.getDay() == 6,""]}
});
</script>

Two important things:

1. The code above is a Jquery command for the datepicker so the code must be place after their dependent libraries (just place it close to the body tage in footer.php or call it trough functions.php).

2. You must target your date field correctly and to do so the jquery id used must match the id of the field in the your form. Based on the jquery above just place the id "RemoveSundaysAndMondays" on your date field.

If it work don't forget to tell me ok?

**Comment by amyling** [comment]
Hi Hansmosl-

Thanks! I forgot to respond. This worked great!

Amy
