### ISSUE TITLE
Not fully compatible with Contact Form 7 v. 4.6

### ISSUE THREAD

**Issue by Psithief** [relu/contact-form-7-datepicker#164]
Contact Form 7 "complains" about the following on every page under `/wp-admin/` if this plugin is enabled. Many other plugins need to make similar changes, it seems.

`Notice: wpcf7_add_shortcode is deprecated since Contact Form 7 version 4.6! Use wpcf7_add_form_tag instead. ...` appears four times.

**Comment by relu** [comment]
I'm no longer actively maintaining this plugin, but do feel free to send a PR and I'll gladly merge in any such fixes and release a new version.

**Comment by prbprado** [comment]
Hi, how I could resolve this problem?

**Comment by relu** [comment]
Resolved by @imelgrat in PR #166, #167 #168.
