### ISSUE TITLE
This project should be deprecated

### ISSUE THREAD

**Issue by jan--m** [relu/contact-form-7-datepicker#193]
It caused my form to stop functioning after a CF7 upgrade earlier this year (due to an invalid European date format). Now - after the disabling the datepicker plugin - not only does the form work properly, but another date picker shows up (built in jquery?) and works great!

**Comment by relu** [comment]
It is already deprecated and I have no intention to maintain it any longer. The date picker you're seeing is probably the browser vendored one.

**Comment by jan--m** [comment]
Alright, but I don't see that mentioned anywhere - neither in the readme nor in the WP plugin page. I think the maintenance status should be highlighted in both places. Attaching a screenshot of the built-in date picker: 
![screen shot 2017-05-29 at 15 50 59](https://cloud.githubusercontent.com/assets/5662391/26552268/bef46e0c-4486-11e7-8d8a-a257a1b37707.png)

**Comment by relu** [comment]
From what I see they don't offer such an option i.e. to mark the plugin as no longer maintained. I did add this information to the repository description in github though, it seems people don't really see that unfortunately.

**Comment by benpolinsky** [comment]
I mean, you could put it on the readme here.
