### ISSUE TITLE
hide past dates

### ISSUE THREAD

**Issue by ghost** [relu/contact-form-7-datepicker#24]
Hello - I would like the calendar to block dates past.  Could you help me modify that please?  Many thanks!

**Comment by ravimane91** [comment]
hello sir , i have been taken two date field , they are depending on each other. how to deal second date feild value is max than first one in CF-7 data picker

**Comment by prakcode** [comment]
I have 3 date ranges Start date ,End date and  Work date ..

Condition : end date should not be select the past date from start date 
means , start date is not greater than end date,
End date is not less than Start date
Work date is not less than End date
how to do on CF7 ?
