### ISSUE TITLE
Disable monday and tuesday

### ISSUE THREAD

**Issue by Joneses** [relu/contact-form-7-datepicker#37]
Hi, Is it possbiel to disable mondays and tuesdays?

**Comment by otaviobonder** [comment]
Hi guys, I added the id in the form 7 editor and tried to add the script to the form 7 additional settings and to the footer.php, but there is no way to make it work.

Can anybody help me? 

My contact form 7 settings: [date* id:16 min-date:0 date min:today "Data"]

The script under footer.php:

<script>
jQuery(function($){
  var holidayDates = ["1-5", "25-12"]; // define your holidays here
  $("#16").datepicker({
    beforeShowDay: function(date) {
    var day = date.getDay(),
          dm = date.getDate() + "-" + (date.getMonth() + 1);
    var isHoliday = ($.inArray(dm, holidayDates) != -1);
    return [day != 0 && !isHoliday];
  }});
});
</script>

Thanks!

**Comment by naazg** [comment]
Hello, Sorry i know it take too long. but i used the above code to disable Friday and Saturday as a holidays.. I tried with the option available in the plugin but its only disabling Sat and Sun.. while here the holidays are Fri and Sat.. The code works great.. but the issue with this is it disable the time bar. Now i am unable to select the timing.... can anyone help me.

**Comment by mdkz1** [comment]
@relu Thanks man .....

**Comment by ng-design** [comment]
Can anyone help me modify this code? I've been trying to get relu's example to work for the past two days, without much luck.

Specifically, I want to disable all days that aren't Wednesday. (I know, at this point, it's a bit pointless to even have a calendar, but that's what I've been asked to do.)

If anyone could post the exact code I need to insert, you'd really be helping me out. Thank you in advance!

**Comment by naazg** [comment]
Hello Spooner street, 

Below is the code. I disabled friday and saturday using the below code

```
$("#56off").datepicker({
    beforeShowDay: function(date) {
        var day = date.getDay();
        return [(day != 5 && day != 6)];
    }
});
```
where #56off is the id of the date field... if you still couldn't figure out let me know i will try to write a code for you which will enable Wednesday only. but the code is very easy you can understand.

Hope that's help.

Naaz

**Comment by ng-design** [comment]
Thanks for reaching out to help, naazg. I'll give this a try.

**Comment by simonemontrucchio** [comment]
Hi @relu , hi @naazg , I need to disable by default some months, so I found the code to disable specific days of the week and I would like to use is as starting to disable months.
The problem is even the code I found here doesn't work, it doesn't disable days :(
Could you please help me?
Many thanks

**Comment by RedMapleMedia** [comment]
This code doesn't work for me? Can someone tell me why please? Trying to block out Friday/Saturday on "Contact Form 7" date object.

+++ HTML

< input type="date" name="datepicker1" value="" class="wpcf7-form-control wpcf7-date wpcf7-validates-as-required wpcf7-validates-as-date" id="datepicker1" aria-required="true" aria-invalid="false" >

+++ JS

$("#datepicker1").datepicker({
    beforeShowDay: function(date) {
        var day = date.getDay();
        return [(day != 5 && day != 6)];
    }
});

**Comment by Karanpawars** [comment]
how to disable specific month on this page http://www.ecovillage.org.in/day-tour/.
Please help me i have used contact form 7

**Comment by Eugene-pro-19** [comment]
https://stackoverflow.com/questions/53983437/need-to-disable-holidays-and-day-in-datepicker-contact-form-7/53997477?noredirect=1#comment94863952_53997477

i am unable to get solution following **relu** tips

https://wordpress.org/support/topic/need-to-disable-holidays-and-day-in-datepicker-contact-form-7/

**Comment by TomasHurtz** [comment]
I am not exactly sure about disabling Monday / Tuesday, but this might be useful to you in terms of how to target the right page, the right field etc :  https://github.com/relu/contact-form-7-datepicker/issues/183#issuecomment-487418189
