### ISSUE TITLE
disable past dates

### ISSUE THREAD

**Issue by Kostaslim** [relu/contact-form-7-datepicker#44]
Hello
I would like to ask how  i disable past dates on datepicker? 
Thanks in advance

Kostas

**Comment by jadra02** [comment]
Hi,

I am creating a small school project, wher i m using the contact form 7.

This is the cade I have learn.

<div class="form-row">
                <div class="form-row-group--date">
                    <div class="form-row-label">Delivery Date</div>
                    <div class="form-row-group">
                        <div class="datetimepicker-wrap">
                            [text deliverydate class:form-control class:datetimepicker]
                        </div>

Where do i insert the code to ristrict back date selection of date.

Will appreceat your help.

**Comment by jadra02** [comment]
```
<div class="form-row">
                <div class="form-row-group--date">
                    <div class="form-row-label">Delivery Date</div>
                    <div class="form-row-group">
                        <div class="datetimepicker-wrap">
                            [text deliverydate class:form-control class:datetimepicker]
                        </div>``
```
