### ISSUE TITLE
Date Format dd/mm/yy displays as invalid where day > 12

### ISSUE THREAD

**Issue by jkmccann** [relu/contact-form-7-datepicker#49]
Hi,

I have a date field in CF7 that is defined as:

<p> Date of course<br />
[date* CourseDate date-format:dd/mm/yy] </p>

However, it rejects any days > 12 e.g 15/03/13

I've also tried 
<p> Date of course<br />
[date\* CourseDate date-format:dd/mm/yyyy] </p>  but this also generates an error.

**Comment by batikiotis** [comment]
Hello, does this solution works today?
