### ISSUE TITLE
AM/PM and Time Zone are not working

### ISSUE THREAD

**Issue by tyroneprieto** [relu/contact-form-7-datepicker#63]
DateTime field AM/PM, and Time Zone are not working. Kindly check and fix.

**Comment by sanju31** [comment]
hi relu,
its not working for me
see [appointment-time time-format:hh:mm_tt] this is my code where appointment-time is my variable name.
Please help me to solve this issue.
Thank you

**Comment by relu** [comment]
You don't add the time format in the mail field, you add it to the form field. 

```
[time appointment-time id:appointment-time time-format:hh:mm_tt]
```

**Comment by sanju31** [comment]
hi, thanks for your reply but it is still not working, time is in 24 hours format
like, if i entered 2.00 PM then it display 14.00 in mail.

**Comment by tindawala** [comment]
Hi! I am having the same issue...tried various things and it's still not working.
[datetime* eventdate autocomplete:off date-format:dd/mm/yy time-format:hh:mm_tt]

What am i doing wrong?

T
